apiVersion: v1
kind: Service
metadata: 
  name: frontend-service
spec:
  selector:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/component: frontend
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
