apiVersion: v1
kind: Pod
metadata:
  name: colorapp-by-secret
  labels:
    app: color-app
    owner: bhavin
spec:
  containers:
  - image: mmumshad/simple-webapp-color:latest
    env:
    - name: APP_COLOR
      valueFrom: 
        secretKeyRef:
          name: fav-color-secret
          key: fav-color
    #args: ["$(APP_COLOR)"] #as a backup if appn accepts only  commandline
    name: colorapp3
    ports:
    - containerPort: 8080
      protocol: TCP